import Foundation
import Testing

@testable import PipedKit

@Test func detectsAV1VideoStreamAvailability() {
    func detail(_ streams: [PipedKit.MediaStream]?) -> VideoDetail {
        VideoDetail(
            title: "x", description: nil, uploader: nil, uploaderURL: nil,
            uploaderAvatar: nil, thumbnailURL: nil, hls: "https://example.com/hls.m3u8",
            duration: 1, views: nil, likes: nil, uploaded: nil,
            uploaderVerified: nil, uploaderSubscriberCount: nil, creators: nil, livestream: nil,
            chapters: nil, videoStreams: streams,
            audioStreams: nil, subtitles: nil, relatedStreams: nil, category: nil, tags: nil)
    }
    func stream(_ codec: String) -> PipedKit.MediaStream {
        PipedKit.MediaStream(
            url: "https://example.com/v.mp4", format: "MP4", quality: "1080p",
            mimeType: "video/mp4", codec: codec, videoOnly: true, bitrate: nil,
            width: 1920, height: 1080, fps: 30)
    }

    // HLS-only extraction (the common case): no AV1 HLS attempt should be made.
    #expect(detail([]).hasAV1VideoStream == false)
    #expect(detail(nil).hasAV1VideoStream == false)
    // Only H.264 adaptive streams — still no AV1 master to build.
    #expect(detail([stream("avc1.640028")]).hasAV1VideoStream == false)
    // At least one AV1 stream — the AV1 HLS endpoint can serve a master.
    #expect(detail([stream("avc1.640028"), stream("av01.0.12M.08")]).hasAV1VideoStream)
}

@Test func prefersHLSWhenPresent() {
    let detail = VideoDetail(
        title: "x", description: nil, uploader: nil, uploaderURL: nil,
        uploaderAvatar: nil, thumbnailURL: nil,
        hls: "https://example.com/master.m3u8",
        duration: 1, views: nil, likes: nil, uploaded: nil,
        uploaderVerified: nil, uploaderSubscriberCount: nil, creators: nil, livestream: nil,
        chapters: nil,
        videoStreams: [
            MediaStream(
                url: "https://example.com/360.mp4", format: "MP4",
                quality: "360p", mimeType: "video/mp4", codec: nil,
                videoOnly: false, bitrate: nil, width: nil, height: 360, fps: nil)
        ],
        audioStreams: nil, subtitles: nil, relatedStreams: nil, category: nil, tags: nil)
    #expect(detail.playableURL?.absoluteString == "https://example.com/master.m3u8")
}

@Test func fallsBackToHighestProgressive() {
    let detail = VideoDetail(
        title: "x", description: nil, uploader: nil, uploaderURL: nil,
        uploaderAvatar: nil, thumbnailURL: nil, hls: "",
        duration: 1, views: nil, likes: nil, uploaded: nil,
        uploaderVerified: nil, uploaderSubscriberCount: nil, creators: nil, livestream: nil,
        chapters: nil,
        videoStreams: [
            MediaStream(
                url: "https://example.com/360.mp4", format: "MP4", quality: "360p",
                mimeType: "video/mp4", codec: nil, videoOnly: false, bitrate: nil,
                width: nil, height: 360, fps: nil),
            MediaStream(
                url: "https://example.com/720.mp4", format: "MP4", quality: "720p",
                mimeType: "video/mp4", codec: nil, videoOnly: false, bitrate: nil,
                width: nil, height: 720, fps: nil),
            MediaStream(
                url: "https://example.com/1080.mp4", format: "MP4", quality: "1080p",
                mimeType: "video/mp4", codec: nil, videoOnly: true, bitrate: nil,
                width: nil, height: 1080, fps: nil),  // video-only, must be ignored
        ],
        audioStreams: nil, subtitles: nil, relatedStreams: nil, category: nil, tags: nil)
    #expect(detail.playableURL?.absoluteString == "https://example.com/720.mp4")
}

@Test func decodesAndPrefersSubtitles() throws {
    let json = """
        {
          "subtitles": [
            {"autoGenerated": true, "code": "en", "mimeType": "application/ttml+xml", "name": "English auto", "url": "https://example.com/auto.ttml"},
            {"autoGenerated": false, "code": "en-US", "mimeType": "application/ttml+xml", "name": "English", "url": "https://example.com/manual.ttml"}
          ]
        }
        """.data(using: .utf8)!
    let detail = try JSONDecoder().decode(VideoDetail.self, from: json)
    let preferred = try #require(detail.preferredSubtitle(preferredLanguages: ["en-US"]))
    #expect(preferred.url == "https://example.com/manual.ttml")
}

@Test func decodesAudioLanguageMetadata() throws {
    let json = """
        {
          "url": "https://example.com/en.m4a",
          "mimeType": "audio/mp4",
          "bitrate": 128000,
          "audioTrackId": "en.0",
          "audioTrackName": "English original",
          "audioTrackType": "original",
          "audioTrackLocale": "en-US",
          "language": "English",
          "languageCode": "en",
          "name": "English"
        }
        """.data(using: .utf8)!

    let stream = try JSONDecoder().decode(MediaStream.self, from: json)
    #expect(stream.audioTrackName == "English original")
    #expect(stream.audioTrackType == "original")
    #expect(stream.audioTrackLocale == "en-US")
    #expect(stream.languageCode == "en")
    #expect(stream.audioLanguageHints.contains("English original"))
    #expect(stream.audioLanguageHints.contains("en-US"))
}

@Test func prefersAudioLanguageOverBitrateForComposedSource() throws {
    let detail = VideoDetail(
        title: "x", description: nil, uploader: nil, uploaderURL: nil,
        uploaderAvatar: nil, thumbnailURL: nil, hls: nil,
        duration: 1, views: nil, likes: nil, uploaded: nil,
        uploaderVerified: nil, uploaderSubscriberCount: nil, creators: nil, livestream: nil,
        chapters: nil,
        videoStreams: [
            MediaStream(
                url: "https://example.com/1080.mp4", format: "MP4", quality: "1080p",
                mimeType: "video/mp4", codec: "avc1.640028", videoOnly: true,
                bitrate: nil, width: 1920, height: 1080, fps: 30)
        ],
        audioStreams: [
            MediaStream(
                url: "https://example.com/es-dubbed.m4a", format: "M4A", quality: nil,
                mimeType: "audio/mp4", codec: nil, videoOnly: nil, bitrate: 256000,
                width: nil, height: nil, fps: nil,
                audioTrackName: "Spanish dubbed", audioTrackType: "dubbed", languageCode: "es"),
            MediaStream(
                url: "https://example.com/en-original.m4a", format: "M4A", quality: nil,
                mimeType: "audio/mp4", codec: nil, videoOnly: nil, bitrate: 128000,
                width: nil, height: nil, fps: nil,
                audioTrackName: "English original", audioTrackType: "original", languageCode: "en"),
        ],
        subtitles: nil, relatedStreams: nil, category: nil, tags: nil)

    let source = try #require(detail.bestComposedSource(allowAV1: false, preferredLanguages: ["en-US"]))
    #expect(source.audio.absoluteString == "https://example.com/en-original.m4a")
    #expect(
        VideoDetail.audioScore(detail.audioStreams![1], preferredLanguages: ["en-US"])
            > VideoDetail.audioScore(detail.audioStreams![0], preferredLanguages: ["en-US"]))
}

// MARK: - Stream selection helpers

private func makeDetail(
    hls: String? = nil,
    videoStreams: [PipedKit.MediaStream]? = nil,
    audioStreams: [PipedKit.MediaStream]? = nil,
    subtitles: [Subtitle]? = nil
) -> VideoDetail {
    VideoDetail(
        title: "x", description: nil, uploader: nil, uploaderURL: nil,
        uploaderAvatar: nil, thumbnailURL: nil, hls: hls,
        duration: 1, views: nil, likes: nil, uploaded: nil,
        uploaderVerified: nil, uploaderSubscriberCount: nil, creators: nil, livestream: nil,
        chapters: nil, videoStreams: videoStreams, audioStreams: audioStreams,
        subtitles: subtitles, relatedStreams: nil, category: nil, tags: nil)
}

private func makeVideoStream(
    url: String, mime: String = "video/mp4", codec: String? = "avc1.640028",
    videoOnly: Bool = true, height: Int? = nil
) -> PipedKit.MediaStream {
    PipedKit.MediaStream(
        url: url, format: nil, quality: nil, mimeType: mime, codec: codec,
        videoOnly: videoOnly, bitrate: nil, width: nil, height: height, fps: nil)
}

@Test func codecLessH264FallbackRequiresVideoMime() {
    let progressiveVideo = makeVideoStream(url: "https://example.com/v.mp4", codec: "", videoOnly: false)
    #expect(progressiveVideo.isH264)

    let audio = makeVideoStream(url: "https://example.com/a.m4a", mime: "audio/mp4", codec: "", videoOnly: false)
    #expect(!audio.isH264)
    #expect(audio.isPlayableAudio)

    let av1 = makeVideoStream(url: "https://example.com/v.mp4", codec: "av01.0.12M.08")
    #expect(!av1.isH264)
    #expect(makeVideoStream(url: "https://example.com/v.mp4").isH264)
}

@Test func bestProgressiveDownloadSkipsVP9AndWebM() throws {
    let detail = makeDetail(videoStreams: [
        makeVideoStream(
            url: "https://example.com/1080.webm", mime: "video/webm", codec: "vp9", videoOnly: false, height: 1080),
        makeVideoStream(url: "https://example.com/720.mp4", videoOnly: false, height: 720),
        makeVideoStream(url: "https://example.com/2160.mp4", videoOnly: true, height: 2160),
    ])
    let download = try #require(detail.bestProgressiveDownload)
    #expect(download.url.absoluteString == "https://example.com/720.mp4")
    #expect(download.height == 720)

    let vp9Only = makeDetail(videoStreams: [
        makeVideoStream(
            url: "https://example.com/1080.webm", mime: "video/webm", codec: "vp9", videoOnly: false, height: 1080)
    ])
    #expect(vp9Only.bestProgressiveDownload == nil)
}

@Test func bestComposedSourceUsesAV1OnlyWhenAllowed() throws {
    let audio = PipedKit.MediaStream(
        url: "https://example.com/a.m4a", format: nil, quality: nil, mimeType: "audio/mp4",
        codec: nil, videoOnly: nil, bitrate: 128_000, width: nil, height: nil, fps: nil)
    let detail = makeDetail(
        videoStreams: [
            makeVideoStream(url: "https://example.com/1080-h264.mp4", height: 1080),
            makeVideoStream(url: "https://example.com/2160-av1.mp4", codec: "av01.0.12M.08", height: 2160),
        ],
        audioStreams: [audio])

    let withAV1 = try #require(detail.bestComposedSource(allowAV1: true, preferredLanguages: ["en"]))
    #expect(withAV1.video.absoluteString == "https://example.com/2160-av1.mp4")
    #expect(withAV1.height == 2160)

    let withoutAV1 = try #require(detail.bestComposedSource(allowAV1: false, preferredLanguages: ["en"]))
    #expect(withoutAV1.video.absoluteString == "https://example.com/1080-h264.mp4")
    #expect(withoutAV1.height == 1080)
}

@Test func bestComposedSourceReturnsNilWithoutPlayableAudio() {
    let opus = PipedKit.MediaStream(
        url: "https://example.com/a.webm", format: nil, quality: nil, mimeType: "audio/webm",
        codec: "opus", videoOnly: nil, bitrate: 160_000, width: nil, height: nil, fps: nil)
    let detail = makeDetail(
        videoStreams: [makeVideoStream(url: "https://example.com/1080.mp4", height: 1080)],
        audioStreams: [opus])
    #expect(detail.bestComposedSource(allowAV1: true, preferredLanguages: ["en"]) == nil)
}

@Test func reportsMaxAV1AndNonAV1StreamHeights() {
    let detail = makeDetail(videoStreams: [
        makeVideoStream(url: "https://example.com/1440-av1.mp4", codec: "av01.0.12M.08", height: 1440),
        makeVideoStream(url: "https://example.com/2160-av1.mp4", codec: "av01.0.12M.08", height: 2160),
        makeVideoStream(url: "https://example.com/1080-h264.mp4", height: 1080),
        makeVideoStream(url: "https://example.com/720-h264.mp4", height: 720),
    ])
    #expect(detail.maxAV1VideoStreamHeight == 2160)
    #expect(detail.maxNonAV1VideoStreamHeight == 1080)

    #expect(makeDetail(videoStreams: []).maxAV1VideoStreamHeight == nil)
    #expect(makeDetail(videoStreams: nil).maxNonAV1VideoStreamHeight == nil)
}

// MARK: - Subtitle preference

@Test func subtitleNameMatchingUsesWordBoundaries() throws {
    let detail = makeDetail(subtitles: [
        Subtitle(
            autoGenerated: false, code: "", mimeType: nil,
            name: "English (United States)", url: "https://example.com/en.ttml"),
        Subtitle(
            autoGenerated: false, code: "fr", mimeType: nil,
            name: "French", url: "https://example.com/fr.ttml"),
        Subtitle(
            autoGenerated: false, code: "es", mimeType: nil,
            name: "Spanish", url: "https://example.com/es.ttml"),
    ])
    // "French" contains the substring "en"; a word-boundary match must not rank it
    // above (or tied with) the actual English track for an English-preferring user.
    let preferred = try #require(detail.preferredSubtitle(preferredLanguages: ["en"]))
    #expect(preferred.name == "English (United States)")
}

@Test func preferredSubtitleFallsBackToBaseEnglishCode() throws {
    let detail = makeDetail(subtitles: [
        Subtitle(
            autoGenerated: false, code: "fr", mimeType: nil,
            name: "French", url: "https://example.com/fr.ttml"),
        Subtitle(
            autoGenerated: false, code: "en", mimeType: nil,
            name: "English", url: "https://example.com/en.ttml"),
    ])
    let preferred = try #require(detail.preferredSubtitle(preferredLanguages: ["en-GB"]))
    #expect(preferred.code == "en")
}
