import Foundation
import Testing

@testable import PipedKit

@Test func decodesVideoChapters() throws {
    let json = """
        {
          "title": "WWDC 2026: Is Siri Actually Good Now?",
          "duration": 6684,
          "chapters": [
            {"title": "Intro", "image": "https://pipedproxy.cmf.sh/intro.jpg", "start": 0},
            {"title": "Did they even test this?", "image": "https://pipedproxy.cmf.sh/test.jpg", "start": 74},
            {"title": "Vibe of WWDC", "start": 220}
          ]
        }
        """.data(using: .utf8)!
    let detail = try JSONDecoder().decode(VideoDetail.self, from: json)
    let chapters = try #require(detail.chapters)
    #expect(chapters.count == 3)
    #expect(chapters[0].title == "Intro")
    #expect(chapters[0].image == "https://pipedproxy.cmf.sh/intro.jpg")
    #expect(chapters[0].start == 0)
    #expect(chapters[1].start == 74)
    #expect(chapters[2].title == "Vibe of WWDC")
}

@Test func decodesVideoChaptersLossily() throws {
    let json = """
        {
          "title": "Chapter test",
          "chapters": [
            {"title": "Intro", "start": 0},
            {"title": "Bad", "start": "not-a-number"},
            "bad element",
            {"title": "Main", "start": 42}
          ]
        }
        """.data(using: .utf8)!
    let detail = try JSONDecoder().decode(VideoDetail.self, from: json)
    let chapters = try #require(detail.chapters)
    #expect(chapters.map(\.title) == ["Intro", "Main"])
    #expect(chapters.map(\.start) == [0, 42])
}

@Test func decodesNullVideoChaptersAsMissing() throws {
    let json = #"{"title":"Chapter test","chapters":null}"#.data(using: .utf8)!
    let detail = try JSONDecoder().decode(VideoDetail.self, from: json)
    #expect(detail.chapters == nil)
}

@Test func decodesVideoCreators() throws {
    let json = """
        {
          "uploader": "Main Channel",
          "uploaderUrl": "/channel/UCmain",
          "creators": [
            {"name": "Main Channel", "url": "/channel/UCmain", "avatar": "https://example.com/main.jpg", "role": "owner"},
            {"name": "Other Creator", "url": "/channel/UCother", "avatar": "https://example.com/other.jpg", "role": "collaborator"}
          ]
        }
        """.data(using: .utf8)!
    let detail = try JSONDecoder().decode(VideoDetail.self, from: json)
    let creators = try #require(detail.creators)
    #expect(creators.count == 2)
    #expect(creators[0].name == "Main Channel")
    #expect(creators[0].channelID == "UCmain")
    #expect(creators[1].avatar == "https://example.com/other.jpg")
    #expect(creators[1].role == "collaborator")
}

// MARK: - Lossy page decoding

@Test func decodesVideoDetailStreamsAndRelatedLossily() throws {
    let json = """
        {
          "title": "Lossy test",
          "videoStreams": [
            {"url": "https://example.com/1080.mp4", "mimeType": "video/mp4", "codec": "avc1.640028", "videoOnly": true, "height": 1080},
            {"url": 12345},
            {"url": "https://example.com/720.mp4", "mimeType": "video/mp4", "codec": "avc1.640028", "videoOnly": true, "height": 720}
          ],
          "audioStreams": [
            {"url": "https://example.com/a.m4a", "mimeType": "audio/mp4", "bitrate": 128000},
            "junk"
          ],
          "subtitles": [
            {"code": "en", "name": "English", "url": "https://example.com/en.ttml"},
            {"autoGenerated": "not-a-bool"}
          ],
          "relatedStreams": [
            {"url": "/watch?v=good1", "type": "stream", "title": "Good"},
            {"url": 42},
            {"url": "/watch?v=good2", "type": "stream", "title": "Also good"}
          ]
        }
        """.data(using: .utf8)!

    let detail = try JSONDecoder().decode(VideoDetail.self, from: json)
    #expect(detail.videoStreams?.compactMap(\.height) == [1080, 720])
    #expect(detail.audioStreams?.count == 1)
    #expect(detail.subtitles?.compactMap(\.code) == ["en"])
    #expect(detail.relatedStreams?.compactMap(\.videoID) == ["good1", "good2"])
}
