import Foundation

extension VideoDetail {
    /// The video's real width/height ratio, or 16:9 when dimensions are absent.
    public var aspectRatio: Double {
        if let stream = (videoStreams ?? []).first(where: { ($0.width ?? 0) > 0 && ($0.height ?? 0) > 0 }),
            let width = stream.width,
            let height = stream.height
        {
            return Double(width) / Double(height)
        }
        return 16.0 / 9.0
    }

    /// The best URL AVPlayer can play directly.
    public var playableURL: URL? {
        if let hls, !hls.isEmpty, let url = URL(string: hls) { return url }
        let best = (videoStreams ?? [])
            .filter { $0.isProgressive && ($0.url?.isEmpty == false) }
            .max { ($0.height ?? 0) < ($1.height ?? 0) }
        guard let rawURL = best?.url else { return nil }
        return URL(string: rawURL)
    }

    /// The best compatible single-file stream for an offline download.
    public var bestProgressiveDownload: (url: URL, height: Int)? {
        let best = (videoStreams ?? [])
            .filter { $0.isProgressive && !$0.isVP9OrWebM && ($0.url?.isEmpty == false) }
            .max { ($0.height ?? 0) < ($1.height ?? 0) }
        guard let stream = best,
            let rawURL = stream.url,
            let url = URL(string: rawURL)
        else { return nil }
        return (url, stream.height ?? 0)
    }

    public var hasAV1VideoStream: Bool {
        (videoStreams ?? []).contains { $0.isAV1 }
    }

    public var maxAV1VideoStreamHeight: Int? {
        (videoStreams ?? []).filter(\.isAV1).compactMap(\.height).max()
    }

    public var maxNonAV1VideoStreamHeight: Int? {
        (videoStreams ?? []).filter { !$0.isAV1 }.compactMap(\.height).max()
    }

    public func bestComposedSource(
        allowAV1: Bool,
        preferredLanguages: [String] = Locale.preferredLanguages
    ) -> (video: URL, audio: URL, height: Int)? {
        let candidates = (videoStreams ?? []).filter { stream in
            guard !stream.isProgressive,
                stream.url?.isEmpty == false,
                !stream.isVP9OrWebM
            else { return false }
            return stream.isH264 || (allowAV1 && stream.isAV1)
        }
        guard let video = candidates.max(by: { ($0.height ?? 0) < ($1.height ?? 0) }),
            let videoURLString = video.url,
            let videoURL = URL(string: videoURLString)
        else { return nil }

        let audio = (audioStreams ?? [])
            .filter { $0.isPlayableAudio && $0.url?.isEmpty == false }
            .max {
                Self.audioScore($0, preferredLanguages: preferredLanguages)
                    < Self.audioScore($1, preferredLanguages: preferredLanguages)
            }
        guard let audioURLString = audio?.url,
            let audioURL = URL(string: audioURLString)
        else { return nil }

        return (videoURL, audioURL, video.height ?? 0)
    }

    public static func audioScore(
        _ stream: MediaStream,
        preferredLanguages: [String] = Locale.preferredLanguages
    ) -> Int {
        let hints = stream.audioLanguageHints.map {
            $0.replacingOccurrences(of: "_", with: "-").lowercased()
        }
        let preferred = preferredLanguagesWithEnglishFallback(preferredLanguages)
        var languageScore = 0
        for (index, language) in preferred.enumerated() {
            let weight = max(0, 1_000 - index * 25)
            if hints.contains(language) {
                languageScore = max(languageScore, weight)
            } else if hints.contains(where: { hint in
                hint.hasPrefix(language + "-")
                    || language.hasPrefix(hint + "-")
                    || hint.localizedStandardContains(languageName(for: language))
            }) {
                languageScore = max(languageScore, weight - 10)
            }
        }
        var result = languageScore * 1_000
        if hints.contains(where: { $0.contains("original") }) {
            result += 500
        }
        if hints.contains(where: { $0.contains("dub") }) {
            result -= 500
        }
        result += min(max(stream.bitrate ?? 0, 0) / 1_000, 499)
        return result
    }

    public func preferredSubtitle(preferredLanguages: [String] = Locale.preferredLanguages) -> Subtitle? {
        let candidates = (subtitles ?? []).filter { $0.usableURL != nil }
        guard !candidates.isEmpty else { return nil }
        let languageCodes = preferredLanguages.flatMap(Self.languageCandidates)

        func score(_ subtitle: Subtitle) -> Int {
            let code = (subtitle.code ?? "").lowercased()
            let name = (subtitle.name ?? "").lowercased()
            var result = subtitle.autoGenerated == true ? 0 : 100
            if languageCodes.contains(code) {
                result += 50
            } else if languageCodes.contains(where: {
                code.hasPrefix($0 + "-") || Self.subtitleNameMatches(name, language: $0)
            }) {
                result += 25
            }
            return result
        }

        return candidates.max { score($0) < score($1) }
    }

    private static func subtitleNameMatches(_ name: String, language: String) -> Bool {
        let words = name.split { !$0.isLetter }
        if words.contains(Substring(language)) { return true }
        return words.contains(Substring(languageName(for: language)))
    }

    private static func languageCandidates(_ identifier: String) -> [String] {
        let lower = identifier.replacingOccurrences(of: "_", with: "-").lowercased()
        var output = [lower]
        if let base = lower.split(separator: "-").first {
            output.append(String(base))
        }
        return output
    }

    private static func preferredLanguagesWithEnglishFallback(_ preferredLanguages: [String]) -> [String] {
        var output: [String] = []
        for language in preferredLanguages.flatMap(languageCandidates) where !output.contains(language) {
            output.append(language)
        }
        for language in ["en-us", "en"] where !output.contains(language) {
            output.append(language)
        }
        return output
    }

    private static func languageName(for language: String) -> String {
        let base = language.split(separator: "-").first.map(String.init) ?? language
        return Locale(identifier: "en_US").localizedString(forLanguageCode: base)?.lowercased() ?? base
    }
}
