import Foundation

public struct VideoCreator: Codable, Hashable, Sendable {
    public let name: String?
    public let url: String?
    public let avatar: String?
    public let role: String?

    public var channelID: String? { PipedID.channel(fromURL: url) }
}

public struct Subtitle: Codable, Hashable, Sendable {
    public let autoGenerated: Bool?
    public let code: String?
    public let mimeType: String?
    public let name: String?
    public let url: String?

    public var usableURL: URL? {
        guard let url, !url.isEmpty else { return nil }
        return URL(string: url)
    }
}

public struct VideoChapter: Codable, Hashable, Identifiable, Sendable {
    public let title: String?
    public let image: String?
    public let start: Int

    public var id: String { "\(start)|\(title ?? "")" }
}

public struct VideoDetail: Codable, Sendable {
    public let title: String?
    public let description: String?
    public let uploader: String?
    public let uploaderURL: String?
    public let uploaderAvatar: String?
    public let thumbnailURL: String?
    public let hls: String?
    public let duration: Int?
    public let views: Int?
    public let likes: Int?
    public let uploaded: Int64?
    public let uploaderVerified: Bool?
    public let uploaderSubscriberCount: Int?
    public let creators: [VideoCreator]?
    public let livestream: Bool?
    public let chapters: [VideoChapter]?
    public let videoStreams: [MediaStream]?
    public let audioStreams: [MediaStream]?
    public let subtitles: [Subtitle]?
    public let relatedStreams: [StreamItem]?
    public let category: String?
    public let tags: [String]?

    enum CodingKeys: String, CodingKey {
        case title, description, uploader
        case uploaderURL = "uploaderUrl"
        case uploaderAvatar
        case thumbnailURL = "thumbnailUrl"
        case hls, duration, views, likes, uploaded, uploaderVerified, uploaderSubscriberCount
        case creators, livestream, chapters, videoStreams, audioStreams, subtitles, relatedStreams
        case category, tags
    }

    public init(
        title: String?,
        description: String?,
        uploader: String?,
        uploaderURL: String?,
        uploaderAvatar: String?,
        thumbnailURL: String?,
        hls: String?,
        duration: Int?,
        views: Int?,
        likes: Int?,
        uploaded: Int64?,
        uploaderVerified: Bool?,
        uploaderSubscriberCount: Int?,
        creators: [VideoCreator]?,
        livestream: Bool?,
        chapters: [VideoChapter]?,
        videoStreams: [MediaStream]?,
        audioStreams: [MediaStream]?,
        subtitles: [Subtitle]?,
        relatedStreams: [StreamItem]?,
        category: String?,
        tags: [String]?
    ) {
        self.title = title
        self.description = description
        self.uploader = uploader
        self.uploaderURL = uploaderURL
        self.uploaderAvatar = uploaderAvatar
        self.thumbnailURL = thumbnailURL
        self.hls = hls
        self.duration = duration
        self.views = views
        self.likes = likes
        self.uploaded = uploaded
        self.uploaderVerified = uploaderVerified
        self.uploaderSubscriberCount = uploaderSubscriberCount
        self.creators = creators
        self.livestream = livestream
        self.chapters = chapters
        self.videoStreams = videoStreams
        self.audioStreams = audioStreams
        self.subtitles = subtitles
        self.relatedStreams = relatedStreams
        self.category = category
        self.tags = tags
    }

    @available(
        *, deprecated,
        renamed:
            "init(title:description:uploader:uploaderURL:uploaderAvatar:thumbnailURL:hls:duration:views:likes:uploaded:uploaderVerified:uploaderSubscriberCount:creators:livestream:chapters:videoStreams:audioStreams:subtitles:relatedStreams:category:tags:)"
    )
    public init(
        title: String?,
        description: String?,
        uploader: String?,
        uploaderUrl: String?,
        uploaderAvatar: String?,
        thumbnailUrl: String?,
        hls: String?,
        duration: Int?,
        views: Int?,
        likes: Int?,
        uploaded: Int64?,
        uploaderVerified: Bool?,
        uploaderSubscriberCount: Int?,
        creators: [VideoCreator]?,
        livestream: Bool?,
        chapters: [VideoChapter]?,
        videoStreams: [MediaStream]?,
        audioStreams: [MediaStream]?,
        subtitles: [Subtitle]?,
        relatedStreams: [StreamItem]?,
        category: String?,
        tags: [String]?
    ) {
        self.init(
            title: title,
            description: description,
            uploader: uploader,
            uploaderURL: uploaderUrl,
            uploaderAvatar: uploaderAvatar,
            thumbnailURL: thumbnailUrl,
            hls: hls,
            duration: duration,
            views: views,
            likes: likes,
            uploaded: uploaded,
            uploaderVerified: uploaderVerified,
            uploaderSubscriberCount: uploaderSubscriberCount,
            creators: creators,
            livestream: livestream,
            chapters: chapters,
            videoStreams: videoStreams,
            audioStreams: audioStreams,
            subtitles: subtitles,
            relatedStreams: relatedStreams,
            category: category,
            tags: tags)
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        self.title = try values.decodeIfPresent(String.self, forKey: .title)
        self.description = try values.decodeIfPresent(String.self, forKey: .description)
        self.uploader = try values.decodeIfPresent(String.self, forKey: .uploader)
        self.uploaderURL = try values.decodeIfPresent(String.self, forKey: .uploaderURL)
        self.uploaderAvatar = try values.decodeIfPresent(String.self, forKey: .uploaderAvatar)
        self.thumbnailURL = try values.decodeIfPresent(String.self, forKey: .thumbnailURL)
        self.hls = try values.decodeIfPresent(String.self, forKey: .hls)
        self.duration = try values.decodeIfPresent(Int.self, forKey: .duration)
        self.views = try values.decodeIfPresent(Int.self, forKey: .views)
        self.likes = try values.decodeIfPresent(Int.self, forKey: .likes)
        self.uploaded = try values.decodeIfPresent(Int64.self, forKey: .uploaded)
        self.uploaderVerified = try values.decodeIfPresent(Bool.self, forKey: .uploaderVerified)
        self.uploaderSubscriberCount = try values.decodeIfPresent(Int.self, forKey: .uploaderSubscriberCount)
        self.creators = try values.decodeIfPresent([VideoCreator].self, forKey: .creators)
        self.livestream = try values.decodeIfPresent(Bool.self, forKey: .livestream)
        self.chapters = try values.decodeLossyArray([VideoChapter].self, forKey: .chapters)
        self.videoStreams = try values.decodeLossyArray([MediaStream].self, forKey: .videoStreams)
        self.audioStreams = try values.decodeLossyArray([MediaStream].self, forKey: .audioStreams)
        self.subtitles = try values.decodeLossyArray([Subtitle].self, forKey: .subtitles)
        self.relatedStreams = try values.decodeLossyArray([StreamItem].self, forKey: .relatedStreams)
        self.category = try values.decodeIfPresent(String.self, forKey: .category)
        self.tags = try values.decodeIfPresent([String].self, forKey: .tags)
    }

    @available(*, deprecated, renamed: "uploaderURL")
    public var uploaderUrl: String? { uploaderURL }

    @available(*, deprecated, renamed: "thumbnailURL")
    public var thumbnailUrl: String? { thumbnailURL }

    public var channelID: String? { PipedID.channel(fromURL: uploaderURL) }
}
